[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 1337
verbosity = 2

# See more config options https://github.com/gakonst/foundry/tree/master/config